### ISSUE TITLE
Loading external sources

### ISSUE THREAD

**Issue by minasouliman** [widgetti/ipyvuetify#189]
I was wondering, is it possible for me to load an external library like [v-calendar](https://vcalendar.io/)?

I saw that there were a couple of examples posted in the past couple of months for loading external sources but I couldn't for the life of me get it to work with this one.

Let me know if I'm completely off-base here and it's not at all possible :)

**Comment by mariobuikhuizen** [comment]
This library seems to be usable only within a javascript build step.

**Comment by minasouliman** [comment]
closing this as I have moved on to using https://ipydatetime.readthedocs.io/en/latest/ instead, which was much easier to intergrate with ipyvuetify
