### ISSUE TITLE
Validating the Render Status of an ipyvuetify component

### ISSUE THREAD

**Issue by Flaminator89** [widgetti/ipyvuetify#195]
Question : I am curious about validating the rendered status of a component.  Lets say I have a 'fruit selector' instance [from the docs](https://ipyvuetify.readthedocs.io/en/latest/template_usage.html), if someone were to misspell `v-select` as `v-selet`, then the template would fail to render but there is no indication of that anywhere or for that matter where the error lies. 

Is there a place that should be looked at to validate whether the template is rendered?  I have tried some vue lifecycle hooks (mounted, errorCaptured, etc.) but they don't seem to raise errors on an invalid template either.

**Comment by mariobuikhuizen** [comment]
You could try to do a dev install of ipyvue. That will give warnings in the browsers console.

I thought I enabled this also in the regular install, but that doesn't seem to work.

**Comment by Flaminator89** [comment]
I'll give that a try and see if I can get it working - thanks!
