### ISSUE TITLE
TextField Validation Rules (Pass function?)

### ISSUE THREAD

**Issue by qjones81** [widgetti/ipyvuetify#219]
I am looking to do some simple form validation in ipyvuetify.  It seems problematic to adopt the examples from vuetify.js directly.  In particular one should be able to pass a function to the rules property so one can run logic to decipher if the input/text field is valid or not.  What is the syntax to accomplish this?

Below is what I have tried:

`v.TextField(label='Name', rules=[self.test], placeholder='First Name')`

```
def test(self):
        return "Invalid"
```

Thanks for the help!

**Comment by TermeHansen** [comment]
As far as I know (maybe it has changed recently), you can not get returns from functions. So for me to yous this I set the rules to point as a variable and then make an update function for that variable that is run on every change:
```
                <v-text-field
                  v-model="temp_str"
                  @change="temp_rule"
                  :rules="[temp_error]"
                  label="Fluid temperature"
                  clearable
                ></v-text-field>
```

and then


```
    def vue_temp_rule(self, v):
        self.temp_error = None
        try:
            self.temp = int(v)
        except Exception as e:
            self.temp_error = 'temperature needs to be an integer'
```

**Comment by qjones81** [comment]
Good deal.  This makes sense.  I was very early on with ipyvuetify and had not experimented with using Templates.  I put this problem to the back, but not I see how this can be done with your method proposed.

Thanks!
