### ISSUE TITLE
Plot in a dialog

### ISSUE THREAD

**Issue by Alexboiboi** [widgetti/ipyvuetify#227]
Hi there,

Just wondering if there is a way to include a plotly FigureWidget in a dialog box ?

Thanks ;)

**Comment by dfguerrerom** [comment]
of course, `FigureWidget` is a `DOMWidget` subclass... 
I have one implementation combining `ipyvuetify` elements with plotly, you can check it here: https://github.com/sepal-contrib/basin-rivers/blob/master/component/tile/dashboard_view.py

**Comment by Alexboiboi** [comment]
Hi @dfguerrerom,

Thanks for your answer! In my case it was just not working because I was using ipywidgets 8.0 which is not yet compatible with plotly.

**Comment by maartenbreddels** [comment]
@dfguerrerom off topic, but just want to say what you are making looks beautiful!

**Comment by dfguerrerom** [comment]
> Hi @dfguerrerom,
> 
> Thanks for your answer! In my case it was just not working because I was using `ipywidgets 8.0` which is not yet compatible with plotly.

good to know that, thanks for sharing it.

> @dfguerrerom off topic, but just want to say what you are making looks beautiful!

Thanks, @maartenbreddels, we are developing several user interfaces based on `ipyvuetify` to display our workflows and we are happy with this framework.

**Comment by Alexboiboi** [comment]
closing this, as answered ;)
