### ISSUE TITLE
Failed to load model class... (PyPI release 1.8.5)

### ISSUE THREAD

**Issue by maread99** [widgetti/ipyvuetify#252]
Hi

I've just upgraded dependencies for this [project](https://github.com/maread99/market_analy) and bumped `ipyvuetify` from 1.8.4 to 1.8.5 (PyPI version numbers). With 1.8.5 I'm getting an error when trying to load widgets. For example...
```python
import ipyvuetify as v
v.Btn(color='primary', children=['Click me'])
```
```
Failed to load model class 'BtnModel' from module 'jupyter-vuetify'
loadClass@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:74977
loadModelClass@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:10729
_make_model@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:7517
new_model@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:5137
handle_comm_open@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:3894
134/v/this._handleCommOpen@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:73393
_handleCommOpen@http://localhost:8888/static/lab/jlab_core.6144df8e3fe03e33f880.js?v=6144df8e3fe03e33f880:2:1001315
```

I am able to load widgets from `ipywidgets`.

I upgraded related packages at the same time as described by the requirements.txt file of [this diff](https://github.com/maread99/market_analy/commit/e75a85566bb18261d51b3a570500ab958c7cda5f).

Reverting `ipyvuetify` to version 1.8.4, whilst leaving all the other packages at the upgraded versions, and all's fine...
```python
import ipyvuetify as v
v.Btn(color='primary', children=['Click me'])
```
![image](https://user-images.githubusercontent.com/56914820/230903031-9db48129-1d55-449f-a6a7-cdd3865d1c56.png)

I tried running the following again, to no avail...
```
jupyter nbextension enable --py --sys-prefix ipyvuetify
```

Given 1.8.5 came out on 21st March and I can't see any other similar issue having been raised, I'm guessing it's something to do with my local environment(?). I was hoping you might have some ideas as to what's going on?

Thank you
Marcus

**Comment by mariobuikhuizen** [comment]
Hi @maread99, have you tried refreshing the browser?

**Comment by maread99** [comment]
Hi @mariobuikhuizen, thanks for replying.

I hadn't, have now, no change I'm afraid.

**Comment by maread99** [comment]
With 1.8.5 I'm getting the load error in JupyterLab although widgets are displaying fine in a Jupyter Notebook **in the same session and in the same browser instance**.

I'm hoping that might give a clue as to where the problem might lie?

**Comment by mariobuikhuizen** [comment]
Which version of JupyterLab?

**Comment by maread99** [comment]
🤦‍♂️ what an idiot. I'm somewhat embarrassed to say I was working in a VE to which JupyterLab 3.6.1 was installed but I was calling it from a global environment that hadn't been updated since God was a lad (I was unwittingly using 3.5.3).

All working now with 3.6.3.

Sorry for wasting any of your time.

Thank you for the replies and for `ipyvuetify`.

**Comment by mariobuikhuizen** [comment]
No worries, we've all been there :sweat_smile:. It should work on 3.5.3 though, but it sounds like JupyterLab 3.5.3 was in a different environment then where ipyvuetify 1.8.5 was installed. The frontend part of ipyvuetify comes from the environment JupyterLab is started in.

**Comment by maread99** [comment]
Thanks @mariobuikhuizen. Quick question to clarify this if I may...

I was starting JupyterLab (3.5.3) in an environment with `ipyvuetify` 1.8.4 installed although the VE I was working in (which the kernel was installed to) had `ipyvuetify` 1.8.5 installed.

If someone was wanting to have only a single copy of JupyterLab installed, are we saying that to avoid any conflict between the frontend and backend the `ipyvuetify` version must be the same in both the VE and the environment in which JupyterLab is started? Would the same be true for `bqplot`?

**Comment by maread99** [comment]
Great. In the installation section of the `market_analy` readme I'd actually written up how using JupyterLab in a different environment was an option, yet it still didn't dawn on me that this was what I was unwittingly doing myself. I've just updated those installation notes. If you get a chance would you mind having a quick look ([here](https://github.com/maread99/market_analy#installation-and-environment)) and letting me know if it makes sense or if I'm misunderstanding something. It's pretty short.

Thanks again, very much appreciated - I certainly feel more comfortable now about offering a project that depends on JupyterLab and various parts of the widgets ecosystem.

**Comment by maartenbreddels** [comment]
Hi Marcus,

There is no need do do `jupyter nbextension enable --py --sys-prefix ipyvuetify`, this is automatic (except for a dev/editable install). For the rest the instructions seem correct.

**Comment by maread99** [comment]
Great, that's for having a look Maarten.

Thank you both for your work on `ipyvuetify` and across the jupyter widgets ecosystem. Wonderful tools.

**Comment by maartenbreddels** [comment]
Thanks!
