### ISSUE TITLE
how did you generated the vuetify_api.json file ? 

### ISSUE THREAD

**Issue by 12rambau** [widgetti/ipyvuetify#270]
If I want to integrate the documentation from the js API directly I would need to wire directly with the vuetify API itself. I realize that for generating the schema of the widgets, you use the `generate_source/vuetify_api.json`. As this file is part of the git repository I assume it's only regenerated when needed, would you mind explaining how you did generated this file ?

**Comment by mariobuikhuizen** [comment]
It's generated by the documentation task of the Vuetify project. I run it by hand when we update the version of Vuetify. I will have to lookup how I do it and add it to the docs.

**Comment by 12rambau** [comment]
Nice, from my side I find the following [json files](https://github.com/vuetifyjs/vuetify/tree/v2-stable/packages/api-generator/src/locale/en) with all the strings corresponding to the docs, so if I can include the parsing of these in the generated json I would just have to modify the template in generate source to have docstring for each trait. 

Regarding the class themselves I'm still looking but that must be in the same area.
