### ISSUE TITLE
vuetify typography classes don't work

### ISSUE THREAD

**Issue by dfguerrerom** [widgetti/ipyvuetify#279]
I'm trying to use some of the typography classes but none of them work.

```python
import ipyvuetify as v
v.Html(tag="div", class_="text-h1",  children = ["I don't work"])
```

it seems a bug to me

**Comment by 12rambau** [comment]
Be careful I think ipyvuetify is not yet wired to the latest version of vuetify. As a consequence it only wire typography prior to v2.3.0 (https://v2.vuetifyjs.com/en/styles/text-and-typography/#typography):

    .display-4
    .display-3
    .display-2
    .display-1
    .headline
    .title
    .subtitle-1
    .subtitle-2
    .body-1
    .body-2
    .caption
    .overline

```python 
import ipyvuetify as v
v.Html(tag="div", class_="display-1",  children = ["I do work"])
```

**Comment by dfguerrerom** [comment]
thank you, I didn't see that huge green message.
