### ISSUE TITLE
input text field for the collection of examples

### ISSUE THREAD

**Issue by joseberlines** [widgetti/ipyvuetify#96]
You might add this example to the collection of examples.
It is a simple Input Text but very convenient. chances are that a user input will be very well welcome:

This example simple updates a global variable called doc with the value of an input text field.

```
import ipyvuetify as v

doc=''
v_nr = v.TextField(label='Enter doc number:', placeholder='Enter your data here')
 
mywidgets = v.Col(children = [v_nr])
 
def on_change_nr(widget, event, data):
    global doc
    doc= v_nr.value
    
v_nr.on_event('change', on_change_nr)

container = v.Container(children=[mywidgets])
display(container)
```

**Comment by guimillet** [comment]
This does not seem to work, since `v_model` is used to access the ipyvuetify widget value (#31).
The TextField example can be summarised as:
```python
v_nr = v.TextField(label='Enter doc number:', placeholder='Enter your data here', v_model='')
```
Then, `v_nr.v_model` returns the textfield value.
